# Generated by Django 5.0.6 on 2024-05-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_difficulty_recipe_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pic',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
